### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Faezan** [CreatureSurvive/consolidation#25]

**Comment by Faezan** [comment]
Badge text color is set to white but still the notification number is red and cannot see the notification count (ive respring). The badge isn't where it is suppose to be. I'm leaving you an email please have a look for better understanding

**Comment by CreatureSurvive** [comment]
@Faezan Hmm, my first thought would be that you have the alpha channel of the color set very low, could you check that? If not then I will look into it right now.

**Comment by Faezan** [comment]
Bache text color is set to #00000 but still it's darken

**Comment by CreatureSurvive** [comment]
Looks like this is a bug in my color library, I'm working on a fix for it right now. As a temporary fix you can adjust the brightness slider just a hair and it will fix the coloring.

**Comment by CreatureSurvive** [comment]
I think I have this fixed, the fix will be in an update of libCSPreferences.

**Comment by Faezan** [comment]
looks like it doesnt work yet. badge background color is red (#FF4747) and
badge text color is white (#000000). it would be great if you keep badge
and text color default

**Comment by CreatureSurvive** [comment]
@Faezan I just released alpha 7 with a few adjustments. Between alpha 7 and the libCSPreferences update, this issue should be fixed.

**Comment by Faezan** [comment]
I have updated and thanks. But seems like still it didn't fix the issue Badge Text Color #FFFFFF but isn't white in color. Unable to see notification count
